# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76f73317288969d48c50eb3b716accae065d67bfd067bc2ce476dbb993bc2775ff3dbd41bf06328f1edb37d2b70b46dc761894768c9e1e84786669b5393753a5

test:
  secret_key_base: 8132b18ac8745109d2ed529fffe2d562b7ea89636924423f1e88d86256c5b43da1b89678e2811bf55e274e58916c6590892046964eb5ebee5d0349cf1f7d7d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
